name: Android CI

on:
  push:
    branches: [ "hauptsächlich" ]
  pull_request:
    branches: [ "hauptsächlich" ]

jobs:
  bauen:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: JDK 17 einrichten
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Erteile die Ausführungsberechtigung für gradlew
        run: chmod +x gradlew
        working-directory: Android

      - name: Mit Gradle erstellen
        run: ./gradlew build
        working-directory: Android



